/** Auto-generated by generateCutGoldenFixtures.py — do not edit by hand. */

export interface CutGoldenFixture {
  width: number;
  height: number;
  rgb: readonly number[];
  base64: string;
  byteLength: number;
  paletteBase64: string | null;
  paletteByteLength: number;
}

export const cutGoldenFixtures = {
  grey_2x2: {
    width: 2,
    height: 2,
    rgb: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128],
    base64: "AgACAAAAAwCCgAADAIKAAA==",
    byteLength: 16,
    paletteBase64: null,
    paletteByteLength: 0,
  },
  black_3x2: {
    width: 3,
    height: 2,
    rgb: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    base64: "AwACAAAAAwCDAAADAIMAAA==",
    byteLength: 16,
    paletteBase64: null,
    paletteByteLength: 0,
  },
  checker_4x4: {
    width: 4,
    height: 4,
    rgb: [255, 255, 255, 0, 0, 0, 255, 255, 255, 0, 0, 0, 0, 0, 0, 255, 255, 255, 0, 0, 0, 255, 255, 255, 255, 255, 255, 0, 0, 0, 255, 255, 255, 0, 0, 0, 0, 0, 0, 255, 255, 255, 0, 0, 0, 255, 255, 255],
    base64: "BAAEAAAABgAEAP8A/wAGAAT/AP8AAAYABAD/AP8ABgAE/wD/AAA=",
    byteLength: 38,
    paletteBase64: null,
    paletteByteLength: 0,
  },
  red_2x2_pal: {
    width: 2,
    height: 2,
    rgb: [255, 0, 0, 255, 0, 0, 255, 0, 0, 255, 0, 0],
    base64: "AgACAAAAAwCCAAADAIIAAA==",
    byteLength: 16,
    paletteBase64: "QUgAAAAACgAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAA/wAAAAAAAAAAAAAAAAAAAAAAAA==",
    paletteByteLength: 64,
  },
} as const satisfies Record<string, CutGoldenFixture>;

export function decodeCutFixtureBase64(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}
