#!/usr/bin/env python3
"""Regenerate pngMemoGoldenFixtures.ts from the raw stitchworld_*.png fixtures.

Source: github.com/AllYarnsAreBeautiful/ayab-patterns, StitchWorld/374.png and
StitchWorld/215.png -- real, human-authored patterns carrying genuine
`AYAB:` row-memo comments (not synthetic test data). Picked because they're
small and, between them, cover both halves of the real-world memo alphabet:
374.png uses only digits, 215.png uses the letter codes ('F'/'N') that
~7% of the 480 AYAB:-tagged patterns in that repo actually use.

Reads the raw PNG bytes already committed alongside this script -- there is
no external dependency to re-derive golden output from (unlike the .pat/.stp
golden fixtures, which shell out to the ayab-desktop Python oracle), since
the Comment tEXt value is read directly from the fixture file itself.
"""

from __future__ import annotations

import base64
import json
import struct
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

FIXTURES = ["stitchworld_374", "stitchworld_215"]


def read_comment(data: bytes) -> str | None:
    offset = 8
    while offset + 8 <= len(data):
        length = struct.unpack(">I", data[offset : offset + 4])[0]
        ctype = data[offset + 4 : offset + 8]
        cdata = data[offset + 8 : offset + 8 + length]
        if ctype == b"tEXt" and cdata.startswith(b"Comment\x00"):
            return cdata[8:].decode("latin1")
        if ctype == b"IEND":
            break
        offset += 12 + length
    return None


def main() -> None:
    golden_map: dict[str, dict[str, object]] = {}
    for name in FIXTURES:
        png_path = SCRIPT_DIR / f"{name}.png"
        data = png_path.read_bytes()
        width, height = struct.unpack(">II", data[16:24])
        comment = read_comment(data)
        assert comment is not None and comment.startswith("AYAB:"), (
            f"{name}.png: expected a real AYAB: Comment chunk"
        )
        memos = list(comment[len("AYAB:") :])
        assert len(memos) == height, (
            f"{name}.png: memo length {len(memos)} != image height {height}"
        )
        golden_map[name] = {
            "width": width,
            "height": height,
            "comment": comment,
            "memos": memos,
            "base64": base64.b64encode(data).decode("ascii"),
        }
        print(f"{name}.png: {width}x{height}, comment={comment!r}")

    ts_lines = [
        "/** Auto-generated by generatePngMemoGoldenFixtures.py — do not edit by hand. */",
        "",
        "export interface PngMemoGoldenFixture {",
        "  width: number;",
        "  height: number;",
        "  comment: string;",
        "  memos: readonly string[];",
        "  base64: string;",
        "}",
        "",
        "export const pngMemoGoldenFixtures = {",
    ]
    for name, golden in golden_map.items():
        ts_lines.append(f"  {name}: {{")
        ts_lines.append(f"    width: {golden['width']},")
        ts_lines.append(f"    height: {golden['height']},")
        ts_lines.append(f"    comment: {json.dumps(golden['comment'])},")
        ts_lines.append(f"    memos: {json.dumps(golden['memos'])},")
        ts_lines.append(f"    base64: {json.dumps(golden['base64'])},")
        ts_lines.append("  },")
    ts_lines.append(
        "} as const satisfies Record<string, PngMemoGoldenFixture>;"
    )
    ts_lines.append("")
    ts_lines.append(
        "export function decodePngMemoFixtureBase64(base64: string): Uint8Array {"
    )
    ts_lines.append("  const binary = atob(base64);")
    ts_lines.append("  const bytes = new Uint8Array(binary.length);")
    ts_lines.append("  for (let i = 0; i < binary.length; i++) {")
    ts_lines.append("    bytes[i] = binary.charCodeAt(i);")
    ts_lines.append("  }")
    ts_lines.append("  return bytes;")
    ts_lines.append("}")
    ts_lines.append("")

    out_ts = SCRIPT_DIR / "pngMemoGoldenFixtures.ts"
    out_ts.write_text("\n".join(ts_lines))
    print(f"wrote {out_ts.name}")


if __name__ == "__main__":
    main()
