#!/usr/bin/env python3
"""Generate .pat fixtures and golden RGB output via ayab-desktop PatPatternConverter."""

from __future__ import annotations

import base64
import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = Path(__file__).resolve().parents[5]


def resolve_ayab_desktop_main() -> Path | None:
    env_path = os.environ.get("AYAB_DESKTOP_PATH")
    if env_path:
        candidate = Path(env_path)
        if candidate.exists():
            return candidate

    candidates = [
        REPO_ROOT.parent / "ayab-desktop" / "src" / "main" / "python" / "main",
        REPO_ROOT / "ayab-desktop" / "src" / "main" / "python" / "main",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


AYAB_MAIN = resolve_ayab_desktop_main()
if AYAB_MAIN is None:
    print(
        "error: ayab-desktop Python sources not found.\n"
        "Clone ayab-desktop as a sibling of ayab-valdi, or set AYAB_DESKTOP_PATH "
        "to ayab-desktop/src/main/python/main.",
        file=sys.stderr,
    )
    sys.exit(1)
sys.path.insert(0, str(AYAB_MAIN))

from ayab.pattern_import import PatPatternConverter  # noqa: E402

PATTERN_START = 0x165


def build_solid_pat(
    width: int,
    height: int,
    color_index: int,
    rgb: tuple[int, int, int],
) -> bytes:
    fe_pos = PATTERN_START + height * 2 + 1
    size = fe_pos + 1
    buf = bytearray([0xFF] * size)
    buf[0:3] = b"D4C"
    buf[0x13A] = width & 0xFF
    buf[0x13B] = (width >> 8) & 0xFF
    buf[0x13C] = height & 0xFF
    buf[0x13D] = (height >> 8) & 0xFF
    buf[color_index + 3] = 0
    buf[0x105] = rgb[2]
    buf[0x106] = rgb[1]
    buf[0x107] = rgb[0]
    pos = PATTERN_START
    for _row in range(height):
        buf[pos] = 0x80 | width
        buf[pos + 1] = color_index
        pos += 2
    buf[fe_pos] = 0xFE
    return bytes(buf)


def build_checker_pat(
    width: int,
    height: int,
    rgb1: tuple[int, int, int],
    rgb2: tuple[int, int, int],
) -> bytes:
    pattern_rows: list[list[int]] = []
    for row in range(height):
        pattern_rows.append(
            [1 if (row + col) % 2 == 0 else 2 for col in range(width)]
        )
    pattern_byte_count = sum(len(row) for row in pattern_rows)
    fe_pos = PATTERN_START + pattern_byte_count + 1
    size = fe_pos + 1
    buf = bytearray([0xFF] * size)
    buf[0:3] = b"D4C"
    buf[0x13A] = width & 0xFF
    buf[0x13B] = (width >> 8) & 0xFF
    buf[0x13C] = height & 0xFF
    buf[0x13D] = (height >> 8) & 0xFF
    buf[4] = 0
    buf[5] = 1
    buf[0x105:0x108] = bytes([rgb1[2], rgb1[1], rgb1[0]])
    buf[0x108:0x10B] = bytes([rgb2[2], rgb2[1], rgb2[0]])
    pos = PATTERN_START
    for row in pattern_rows:
        for color in row:
            buf[pos] = color
            pos += 1
    buf[fe_pos] = 0xFE
    return bytes(buf)


def golden_from_pat(data: bytes) -> dict[str, object]:
    path = SCRIPT_DIR / "_tmp_golden.pat"
    path.write_bytes(data)
    try:
        image = PatPatternConverter(debug=False).pattern2im(str(path))
        rgb = list(image.tobytes())
        return {"width": image.width, "height": image.height, "rgb": rgb}
    finally:
        path.unlink(missing_ok=True)


def main() -> None:
    fixtures = {
        "minimal": build_solid_pat(2, 2, 1, (255, 0, 0)),
        "blue_3x2": build_solid_pat(3, 2, 1, (0, 128, 255)),
        "green_4x4": build_solid_pat(4, 4, 1, (0, 255, 0)),
        "checker_4x4": build_checker_pat(4, 4, (255, 0, 0), (0, 0, 255)),
    }

    golden_map: dict[str, dict[str, object]] = {}
    for name, data in fixtures.items():
        pat_path = SCRIPT_DIR / f"{name}.pat"
        pat_path.write_bytes(data)
        golden = golden_from_pat(data)
        golden_path = SCRIPT_DIR / f"{name}.pat.golden.json"
        golden_path.write_text(json.dumps(golden, indent=2) + "\n")
        golden_map[name] = {
            **golden,
            "base64": base64.b64encode(data).decode("ascii"),
            "byteLength": len(data),
        }
        print(f"wrote {pat_path.name} ({len(data)} bytes)")

    ts_lines = [
        "/** Auto-generated by generatePatGoldenFixtures.py — do not edit by hand. */",
        "",
        "export interface PatGoldenFixture {",
        "  width: number;",
        "  height: number;",
        "  rgb: readonly number[];",
        "  base64: string;",
        "  byteLength: number;",
        "}",
        "",
        "export const patGoldenFixtures = {",
    ]
    for name, golden in golden_map.items():
        ts_lines.append(f"  {name}: {{")
        ts_lines.append(f"    width: {golden['width']},")
        ts_lines.append(f"    height: {golden['height']},")
        ts_lines.append(f"    rgb: {json.dumps(golden['rgb'])},")
        ts_lines.append(f"    base64: {json.dumps(golden['base64'])},")
        ts_lines.append(f"    byteLength: {golden['byteLength']},")
        ts_lines.append("  },")
    ts_lines.append("} as const satisfies Record<string, PatGoldenFixture>;")
    ts_lines.append("")
    ts_lines.append("export function decodePatFixtureBase64(base64: string): Uint8Array {")
    ts_lines.append("  const binary = atob(base64);")
    ts_lines.append("  const bytes = new Uint8Array(binary.length);")
    ts_lines.append("  for (let i = 0; i < binary.length; i++) {")
    ts_lines.append("    bytes[i] = binary.charCodeAt(i);")
    ts_lines.append("  }")
    ts_lines.append("  return bytes;")
    ts_lines.append("}")
    ts_lines.append("")

    out_ts = SCRIPT_DIR / "patGoldenFixtures.ts"
    out_ts.write_text("\n".join(ts_lines))
    print(f"wrote {out_ts.name}")


if __name__ == "__main__":
    main()
