import React from "react";

// Must be the first Valdi import, does a bunch of setup
import { ValdiWebRenderer } from 'ayab_web/src/web_renderer/src/ValdiWebRenderer';

// Register native modules (generated by Valdi compiler, from ayab_web package)
require('ayab_web/src/RegisterNativeModules');

// Populate globalThis.__valdiImageRegistry so bundled PNG assets resolve to URLs on web
require('ayab_web/src/_image_registry');

import { App as AyabApp } from 'ayab_web/src/ayab_valdi/src/App';

class AyabDemo extends React.Component {
  constructor(props) {
    super(props);
    this.elementRef = React.createRef();
  }

  componentDidMount() {
    if (this.elementRef.current) {
      const webRenderer = new ValdiWebRenderer(this.elementRef.current);
      webRenderer.renderRootComponent(
        AyabApp,
        {},
        {},
        {},
      );
    }
  }

  render() {
    return <div ref={this.elementRef} className="ayab-root" />;
  }
}

export default function App() {
  return <AyabDemo />;
}
