#!/usr/bin/env bash
# Fetch Valdi's Bazel registry from the upstream tarball at VALDI_REF.
# Writes src/user.bazelrc and caches under src/.valdi-registry/ (gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src"
REGISTRY="$SRC/.valdi-registry"
STAMP="$REGISTRY/.valdi-ref"
USER_BAZELRC="$SRC/user.bazelrc"

# shellcheck source=.github/valdi-deps.env
source "$ROOT/.github/valdi-deps.env"

if [[ ! "$VALDI_REF" =~ ^[0-9a-f]{40}$ ]]; then
  echo "error: VALDI_REF must be a 40-char commit SHA in .github/valdi-deps.env" >&2
  exit 1
fi

if [[ -f "$STAMP" && "$(cat "$STAMP")" == "$VALDI_REF" && -f "$REGISTRY/bazel_registry.json" && -f "$USER_BAZELRC" ]]; then
  exit 0
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

ARCHIVE="$TMP/valdi.tar.gz"
PREFIX="Valdi-${VALDI_REF}"
TAR_PATH="${PREFIX}/registry"

echo "Fetching Valdi Bazel registry from ${VALDI_REPO}@${VALDI_REF}..."
curl -fsSL "https://github.com/${VALDI_REPO}/archive/${VALDI_REF}.tar.gz" -o "$ARCHIVE"
tar -tzf "$ARCHIVE" "$TAR_PATH" >/dev/null

rm -rf "$REGISTRY"
mkdir -p "$REGISTRY"
tar -xzf "$ARCHIVE" -C "$REGISTRY" --strip-components=2 "$TAR_PATH"
echo "$VALDI_REF" > "$STAMP"

REGISTRY_PATH="$(cd "$REGISTRY" && pwd)"
cat > "$USER_BAZELRC" <<EOF
# Generated by scripts/ensure-valdi-registry.sh — do not commit
# Upstream Valdi Bazel registry @ ${VALDI_REF}
common --registry=file://${REGISTRY_PATH}
EOF

echo "Ready: ${REGISTRY_PATH}"
