#!/usr/bin/env bash
# Vendor the AYAB Uno firmware .hex into
# src/modules/serial/src/firmware/generated/AyabFirmwareUnoHex.ts, recording the
# release tag + sha256 in .github/ayab-firmware.env for provenance.
#
# The firmware can't be fetched live from the running web app: GitHub release
# assets are served from release-assets.githubusercontent.com, which sends no
# Access-Control-Allow-Origin header, so a browser fetch() of the binary is
# blocked by CORS. Vendoring it here (a server-side/CI download, not a browser
# fetch) and bundling it into the JS build sidesteps that entirely.
#
# Usage:
#   ./scripts/pin-ayab-firmware.sh <tag>   # e.g. 1.0.0
#   ./scripts/pin-ayab-firmware.sh         # resolve latest GitHub release
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.github/ayab-firmware.env"
OUT_TS="$ROOT/src/modules/serial/src/firmware/generated/AyabFirmwareUnoHex.ts"
REPO="AllYarnsAreBeautiful/ayab-firmware"
ASSET="ayab_monolithic_uno.hex"

if [[ $# -eq 1 ]]; then
  TAG="$1"
elif [[ $# -eq 0 ]]; then
  echo "Resolving latest release tag from GitHub..."
  TAG="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
    | python3 -c "import json,sys; print(json.load(sys.stdin)['tag_name'])")"
else
  echo "usage: $0 [<tag>]" >&2
  exit 1
fi

echo "Fetching release metadata for ${REPO}@${TAG}..."
RELEASE_JSON="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/tags/${TAG}")"

ASSET_URL="$(python3 -c "
import json, sys
release = json.loads(sys.argv[1])
for asset in release['assets']:
    if asset['name'] == sys.argv[2]:
        print(asset['browser_download_url'])
        break
else:
    sys.exit(f\"error: asset {sys.argv[2]!r} not found in release {sys.argv[3]!r}\")
" "$RELEASE_JSON" "$ASSET" "$TAG")"

TMP_HEX="$(mktemp)"
trap 'rm -f "$TMP_HEX"' EXIT

echo "Downloading ${ASSET} from ${ASSET_URL}..."
curl -fsSL "$ASSET_URL" -o "$TMP_HEX"

SHA256="$(shasum -a 256 "$TMP_HEX" | cut -d' ' -f1)"

mkdir -p "$(dirname "$OUT_TS")"

cat > "$ENV_FILE" <<EOF
# Pinned AYAB Uno firmware version for the in-app Web Serial flasher.
# Update with: ./scripts/pin-ayab-firmware.sh <tag>
AYAB_FIRMWARE_REPO=${REPO}
AYAB_FIRMWARE_TAG=${TAG}
AYAB_FIRMWARE_ASSET=${ASSET}
AYAB_FIRMWARE_SHA256=${SHA256}
EOF

python3 - "$TMP_HEX" "$OUT_TS" "$TAG" "$SHA256" "$REPO" "$ASSET" <<'PY'
import sys

hex_path, out_path, tag, sha256, repo, asset = sys.argv[1:7]

with open(hex_path, "r", encoding="ascii") as f:
    hex_text = f.read().rstrip("\n")

header = f"""/**
 * AUTO-GENERATED by scripts/pin-ayab-firmware.sh - do not edit by hand.
 * Source: {repo} release {tag}, {asset}
 * sha256: {sha256}
 *
 * Embedded as plain text (Intel HEX is already ASCII), while binary image data
 * uses Valdi's byte-exact .bin module entries. This stays human-diffable in git
 * and is bundled into the JS build so
 * it's served same-origin at runtime (see pin-ayab-firmware.sh header for why
 * a live browser fetch of the GitHub release asset doesn't work).
 */
export const AYAB_FIRMWARE_UNO_VERSION = "{tag}";
export const AYAB_FIRMWARE_UNO_SHA256 = "{sha256}";
export const AYAB_FIRMWARE_UNO_HEX = `
"""

with open(out_path, "w", encoding="ascii") as f:
    f.write(header)
    f.write(hex_text)
    f.write("\n`;\n")
PY

echo ""
echo "Updated $ENV_FILE and $OUT_TS"
echo "  Firmware: ${REPO}@${TAG} (${ASSET}, sha256 ${SHA256})"
echo ""
echo "Next: bazel test //modules/serial:test"
